name: Build and Deploy
on:
  push:
    branches:
      - note
  pull_request:
    branches:
      - note

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Build ğŸ”§
        run: |
          export REPOSITORY_NAME=${{ github.repository }}
          npm install
          npm run clean
          npm run meta
          npm run prebuild

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Update Rust
        run: rustup update stable

      - name: Install binaryen
        run: sudo apt-get -y install binaryen

      - name: Install twiggy
        run: cargo install twiggy

      - name: Build WASM ğŸš€
        run: npm run generate

      - name: Build project
        run: npm run build

      - name: Export Static Assets
        run: npm run export && touch dist/.nojekyll

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          PUBLISH_DIR: ./out
          COMMIT_MESSAGE: 'chore: deploy to gh-pages'
